{
 "title": "btb-grafana-dashboard",
 "time": { "from": "2022-01-01T00:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "query": "frser-sqlite-datasource" }
  ]
 },
 "panels": [
  { "title": "${database}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "database" },
  {
   "title": "USD Value Progress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  sum(balance * usd_price) AS \"Bot holdings value\"\nFROM\n  coin_value\nGROUP BY\n  datetime",
     "rawQueryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  sum(balance * usd_price) AS \"Bot holdings value\"\nFROM\n  coin_value\nGROUP BY\n  datetime",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  crypto_trade_amount as \"Value in USD\"\nFROM\n  trade_history\nWHERE\n  state = 'COMPLETE'\n  AND selling = 0",
     "rawQueryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  crypto_trade_amount as \"Value in USD\"\nFROM\n  trade_history\nWHERE\n  state = 'COMPLETE'\n  AND selling = 0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / FIRST_VALUE(crypto_trade_amount) OVER (ORDER BY datetime) - 1) AS \"Change in %\"\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / FIRST_VALUE(crypto_trade_amount) OVER (ORDER BY datetime) - 1) AS \"Change in %\"\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT (*) FROM trade_history WHERE selling=0",
     "rawQueryText": "SELECT COUNT (*) FROM trade_history WHERE selling=0",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Coin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  \nalt_coin_id as \"Current coin\", alt_trade_amount as \"Current Amount\", \n(SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) AS \"Last Amount\", \n(alt_trade_amount / (SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) -1 ) AS \"Change\" \nFROM \ntrade_history \nWHERE\nselling=0 AND alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) \nORDER BY \ndatetime DESC LIMIT 1;",
     "rawQueryText": "SELECT  \nalt_coin_id as \"Current coin\", alt_trade_amount as \"Current Amount\", \n(SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) AS \"Last Amount\", \n(alt_trade_amount / (SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) -1 ) AS \"Change\" \nFROM \ntrade_history \nWHERE\nselling=0 AND alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) \nORDER BY \ndatetime DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Next coin",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT p.to_coin_id as other_coin, ((1-0.001*0.001-0.002) * current_coin_price / (sh.target_ratio *(1+0.01)) / sh.other_coin_price) * 100 as 'percentage' FROM scout_history sh JOIN pairs p ON p.id = sh.pair_id WHERE p.from_coin_id = (SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1) ORDER BY sh.datetime DESC, percentage DESC LIMIT (SELECT count(DISTINCT pairs.to_coin_id) FROM pairs JOIN coins ON coins.symbol = pairs.to_coin_id WHERE coins.enabled = 1 AND pairs.from_coin_id=(SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1))",
     "rawQueryText": "SELECT p.to_coin_id as other_coin, ((1-0.001*0.001-0.002) * current_coin_price / (sh.target_ratio *(1+0.01)) / sh.other_coin_price) * 100 as 'percentage' FROM scout_history sh JOIN pairs p ON p.id = sh.pair_id WHERE p.from_coin_id = (SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1) ORDER BY sh.datetime DESC, percentage DESC LIMIT (SELECT count(DISTINCT pairs.to_coin_id) FROM pairs JOIN coins ON coins.symbol = pairs.to_coin_id WHERE coins.enabled = 1 AND pairs.from_coin_id=(SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1))",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Coins progress",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT \nREPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\nalt_coin_id AS coin, \nalt_trade_amount AS amount\nFROM trade_history\nWHERE state = 'COMPLETE' AND selling = 0",
     "rawQueryText": "SELECT \nREPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\nalt_coin_id AS coin, \nalt_trade_amount AS amount\nFROM trade_history\nWHERE state = 'COMPLETE' AND selling = 0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Progress",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT id as trade_id, REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, alt_coin_id AS coin, alt_trade_amount, crypto_trade_amount AS 'USD value' FROM trade_history WHERE selling=0 ORDER BY datetime DESC",
     "rawQueryText": "SELECT id as trade_id, REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, alt_coin_id AS coin, alt_trade_amount, crypto_trade_amount AS 'USD value' FROM trade_history WHERE selling=0 ORDER BY datetime DESC",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  }
 ]
}